const GamesToPlay = [
    'God Of War',
    'Witcher 3',
    'Witcher 2',
    'Witcher 1',
    'GTA 5',
    'GTA 4',
    'GTA 3',
    'GTA San Andreas',
    'GTA Vice City',
    'L.A Noire',
    'Max Payne 1',
    'Max Payne 2',
    'Max Payne 3',
    'Battlefield 1',
    'Battlefield 3',
    'Battlefield 4',
    'Battlefield 5',
    'Battlefield Hardline',
    'The Long Dark',
    'Dying Light',
    'Just Cause 3',
    'Fallout 4',
    'Heavy Rain',
    'Detroit: Become human',
    'Need for Speed: Most Wanted (2005)',
    'Need for Speed 2015',
    'The Walking Dead 1',
    'The Walking Dead 2',
    'The Walking Dead 3',
    'The Walking Dead 4',
    'Star Wars Battlefront 1',
    'Star Wars Battlefront 2',
    'Star Wars Jedi: Fallen Order',
    'Crysis 1',
    'Crysis 2',
    'Crysis 3',
    'Crysis Warhead',
    'Resident Evil 2 (remaster)',
    'Resident Evil 3 (remaster)',
    'Resident Evil 4 (remaster)',
    'Resident Evil 7',
    'Resident Evil 8',
    'Hotline Miami',
    'TES: Skyrim',
    'RED DEAD REDEMPTION 2',
    'Call Of Duty: Warzone',
    'Call Of Duty Modern Warfare 2',
    'Call Of Duty Modern Warfare 3',
    'Call Of Duty Modern Warfare 4',
    'Call Of Duty Black Ops 1',
    'Call Of Duty Black Ops 2',
    'Rise of the Tomb Raider',
    'Left 4 Dead 2',
    'Half life',
    'Portal 1',
    'Portal 2',
    'Metro 2033',
    'Metro Last Light',
    'Metro Exodus',
    'Minecraft',
    'Forza Horizon 4',
    'Forza Horizon 5',
    'Outlast 1',
    'Outlast 2',
    'Outlast Whistleblower',
    'Terraria',
];

module.exports = GamesToPlay;